# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Experimenting with the Earliests Stages of Planet Formation"
author: Vincent Deguin
logo: Docs/OU_Master_LOGO_BLUE_125mm.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_engine: pdflatex
  latex_documents:
    targetname: Thesis.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/Deugz/nb-thesis  # Online location of your book
  path_to_book: _build/html/  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

html:
  favicon                   : "Docs/SVG_Files/OU_Logo.svg"  
  use_edit_page_button      : true
  use_repository_button     : true
  use_issues_button         : true
  use_multitoc_numbering    : false
  extra_navbar              : ""
  extra_footer: |
  
    <img class="CC_licence" src="https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-nc-sa.svg" alt="Licence CC BY NC SA 2"/>
       
  home_page_in_navbar       : false
  baseurl                   : "https://deugz.github.io/nb-thesis/_build/html/"
  comments:
    hypothesis              : true
    utterances              : 
      repo: "https://github.com/Deugz/nb-thesis"
  announcement              : "Current Version: Feb 2023 ⚠ <u>Thesis Deadline</u>: <strong>October 2023</strong> ⚠"


sphinx:
  config:
    language: en
    bibtex_reference_style: author_year
    html_show_copyright: false
#    latex_toplevel_sectioning: 'part'
    latex_logo: "logo.png" 
  extra_extensions:
  - sphinx_design

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath